mongodb:
    image: mongo:latest
nextbus:
    build: .
    ports:
        - "80"
    links:
        - mongodb
haproxy:
    image: dockercloud/haproxy
    ports:
        - "80:80"
    links:
        - nextbus
